version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-datawarehouse
    env_file: .env
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${password} 
    ports:
      - "${sqlserver_port}:1433"
    volumes:
      - sqlserverdata:/home/sqlserverdata
volumes:
  sqlserverdata: